# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout


      # Yarn:
      - restore_cache:
          keys:
          - yarn-cache-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-cache-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      # Elm:
      - restore_cache:
          keys:
          - elm-cache-{{ checksum "elm-package.json" }}
          # fallback to using the latest cache if no exact match is found
          - elm-cache-

      - run: yarn run build:example

      - save_cache:
          paths:
            - elm-stuff
          key: elm-cache-{{ checksum "elm-package.json" }}


      # Sass:
      - run: cd example && yarn install && yarn run sass main.scss main.css


      # Run tests:
      - run:
          name: Start Elm Live Server
          command: cd ~/repo && yarn run server:example
          background: true

      - run: sleep 5 && yarn test
