# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:6

    working_directory: ~/repo

    steps:
      - checkout


      # Yarn:
      - restore_cache:
          keys:
          - yarn-library-cache-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-library-cache-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: yarn-library-cache-{{ checksum "package.json" }}

      - restore_cache:
          keys:
          - yarn-example-cache-{{ checksum "example/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-example-cache-

      - run: cd ~/repo/example && yarn install && cd ~/repo

      - save_cache:
          paths:
            - example/node_modules
          key: yarn-example-cache-{{ checksum "example/package.json" }}


      # Elm:
      - restore_cache:
          keys:
          - elm-calendar-cache-{{ checksum "elm-package.json" }}
          # fallback to using the latest cache if no exact match is found
          - elm-calendar-cache-

      - restore_cache:
          keys:
          - elm-example-cache-{{ checksum "example/elm-package.json" }}
          # fallback to using the latest cache if no exact match is found
          - elm-example-cache-

      - run: yarn run build:example

      - save_cache:
          paths:
            - elm-stuff
          key: elm-calendar-cache-{{ checksum "elm-package.json" }}

      - save_cache:
          paths:
            - example/elm-stuff
          key: elm-example-cache-{{ checksum "example/elm-package.json" }}


      # Sass:
      - run: cd example && yarn install && yarn run sass main.scss main.css


      # Run tests:
      - run:
          name: Start Elm Live Server
          command: cd ~/repo && yarn run server:example
          background: true

      - run: sleep 5 && yarn test

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: cypress/videos

      - store_artifacts:
          path: cypress/screenshots
